version: '3.7'

services:
  plexamp:
    container_name: plexamp
    image: plexamp:4.10.1
    build:
      context: ./
    devices:
     - "/dev/snd:/dev/snd"
    volumes:
      - "./data:/root/.local/share/Plexamp/Settings"
    network_mode: host
    restart: unless-stopped
